report_dir: "./reports"

service_checks:
  canal:
    service_name: "canal"
    service_user: "canal"

  datax:
    service_name: "datax"
    service_user: "datax"

  dophin-scheduler:
    service_name: "dophin-scheduler"
    service_user: "dolphin"